version: '2'
services: 
  nginx:
    build: .
    container_name: nginx
    networks: 
      - nginx
    ports:
      - "4200:80"
    volumes:
      - ./dist:/usr/share/nginx/html

networks: 
  nginx:
    external: true